// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDEDq7Oxn3UNmVwL4SvODfBvsdWXvxLmE',
    appId: '1:726492452989:web:1783a44ae2fdf2f94c7914',
    messagingSenderId: '726492452989',
    projectId: 'eventapp-839c9',
    authDomain: 'eventapp-839c9.firebaseapp.com',
    storageBucket: 'eventapp-839c9.appspot.com',
    measurementId: 'G-8KY4E7FKTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEs7IorTk6Fb7_rigK9wr3idYMzKxoAgk',
    appId: '1:726492452989:android:8ab19b1df6e887a44c7914',
    messagingSenderId: '726492452989',
    projectId: 'eventapp-839c9',
    storageBucket: 'eventapp-839c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9nw5uLzXaif_kXBjTdCS_F4IYOSYnRTI',
    appId: '1:726492452989:ios:899ec0d46a1b4db84c7914',
    messagingSenderId: '726492452989',
    projectId: 'eventapp-839c9',
    storageBucket: 'eventapp-839c9.appspot.com',
    iosClientId: '726492452989-cavf523vvq2rf78ugsle2q1u4lbm2dme.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9nw5uLzXaif_kXBjTdCS_F4IYOSYnRTI',
    appId: '1:726492452989:ios:837a933325259ef74c7914',
    messagingSenderId: '726492452989',
    projectId: 'eventapp-839c9',
    storageBucket: 'eventapp-839c9.appspot.com',
    iosClientId: '726492452989-b1152qqhnr76s2aaab418bis63dumddi.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApplication1.RunnerTests',
  );
}
